### ISSUE TITLE
Segmentation fault with alpine

### ISSUE THREAD

**Issue by rezen** [awslabs/aws-crt-ruby#43]
Howdy! I've tried aws-crt with multiple ruby versions & multiple alpine versions & end up with segmentation fault each time. In this gist you can see logs from the segmentation fault https://gist.github.com/rezen/eb54ea3e972b09bfae153f2534729dbf

### Steps to Reproduce
**Create Dockerfile**  
```Dockerfile
FROM ruby:3.1.2-alpine3.16

ENV LAMBDA_TASK_ROOT=/var/task
ENV LAMBDA_RUNTIME_DIR=/var/runtime
ENV CRT=true

RUN apk --no-cache  add build-base cmake libffi-dev git bash libstdc++ gcc g++ make gcompat musl
RUN gem install aws_lambda_ric aws-crt:0.1.5 aws-sigv4
RUN ruby -e "require 'aws-sigv4'"
```
**Build image**. 
```sh
docker build -t aws-crt-sad-alpine . > log.txt 2>&1
```

**Comment by bretambrose** [comment]
The CRT libraries do not yet have support  for Musl-based distributions yet.

**Comment by jmklix** [comment]
Sorry, but this repo doesn't currently support alpine linux and we don't currently have any plans to do so. Closing this issue
